services:
    ml-model:
    # depends_on:
    #   - kafka
    #   - zeek
      build: 
        context: .   
      environment:        
          BOOTSTRAP_SERVERS: kafka:9092
          INPUT_TOPIC: zeek-logs
          OUTPUT_TOPIC: alert
          MODEL_PATH: /app/RandomForestModel.sav 
      networks:
        - kafka_network

networks:
    kafka_network: 
      name: kafka_network
      external: true
