version: '3.8'

services:
  zeek:
    image: zeek/zeek
    volumes:
      - ./zeek/extract_logs.zeek:/usr/share/zeek/site/extract_logs.zeek
      - ./data/logs/:/zeek/logs
    cap_add:
      - NET_RAW
    container_name: zeek_container
    network_mode: host
    command: "bash -c 'mkdir -p /zeek/logs && cd /zeek/logs && zeek -i any -C local /usr/share/zeek/site/extract_logs.zeek'"
    restart: unless-stopped

  zeek-log-merger:
    build: ./zeek/merging-logs
    networks:
      - kafka_network
    dns:
      - 8.8.8.8
    volumes:
      - ./data/logs:/logs
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy

  mongoserver:
    image: mongo:latest
    hostname: mongodb
    container_name: mongoserver
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./infras/db/mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: zookeeper
    networks:
      - kafka_network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "zookeeper-shell", "localhost:2181", "ls", "/"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka
    hostname: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - kafka_network
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  model:
    container_name: model
    build:
      context: ./infras/model
      dockerfile: Dockerfile
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - INPUT_TOPIC=zeek-logs
      - OUTPUT_TOPIC=alert
      - MODEL_PATH=/app/RandomForestModel.sav
    networks:
      - kafka_network
    depends_on:
      kafka:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully
    command: ["/app/entrypoint.sh"]
    restart: unless-stopped

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - kafka_network
    ports:
      - 8088:8080
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    restart: unless-stopped

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.8.0
    container_name: init-topics
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka_network
    command: >
      bash -c 'echo Waiting for Kafka to be ready... &&
               kafka-topics --create --topic zeek-logs --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 &&
               kafka-topics --create --topic alert --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 &&
               echo Topics created successfully'
    restart: on-failure

  connect:
    container_name: connect
    build:
      context: ./kafka/kafka-connect/
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./data:/zeek
    networks:
      - kafka_network
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_GROUP_ID: "connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: /usr/share/java
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    restart: unless-stopped

  websocket-server:
    container_name: websocket
    hostname: websocket
    build:
      context: ./infras/websocket
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - kafka_network
    command: gunicorn --worker-class eventlet -w 1 server:app --bind 0.0.0.0:5000 --log-level info
    restart: unless-stopped

  vite-app:
    container_name: vite-app
    build:
      context: ./infras/web-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./infras/web-ui:/app
      - vite_node_modules:/app/node_modules
    depends_on:
      websocket-server:
        condition: service_started
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mongodb:
  mongoconfig:
  vite_node_modules:

networks:
  kafka_network:
    name: kafka_network