services:
     zeek:
        image: zeek/zeek
        volumes:
            - extract_logs.zeek:/usr/share/zeek/site/extract_logs.zeek
            - ../data/logs/:/zeek/logs
        cap_add:
            - NET_RAW
        container_name: zeek_container
        network_mode: host

        command: "bash -c 'mkdir -p /zeek/logs && cd /zeek/logs && zeek -i any local /usr/share/zeek/site/extract_logs.zeek'"
        
