FROM node:16

WORKDIR /db

# RUN apt-get update && apt-get install -y mongodb-clients

# COPY package*.json ./
# RUN npm install

ENV MONGO_SERVER=my-mongodb
ENV MONGO_INITDB_DATABASE=test
ENV MONGO_INITDB_ROOT_USERNAME=admin
# ENV MONGO_INITDB_ROOT_PASSWORD=admin