services:
    tcpdump:
        network_mode: host
        volumes:
            - ./logs:/logs
        image: kaazing/tcpdump
        privileged: true 
        command: [ "-i", "any", "-w", "/logs/webserver.pcap", "-nn"]
        

    curl:
        build:
            # context: ..
            dockerfile: Dockerfile
        network_mode: host
        depends_on:
        - tcpdump
        command: ["sh", "-c", "python curl.py"]

    zeek:
        image: zeek/zeek
        volumes:
            - ./logs:/logs
        working_dir: /logs
        depends_on:
            - tcpdump
        # command: ["sh", "-c", "zeek -r /logs/webserver.pcap"]
        entrypoint: ["sh", "-c", "zeek -b -r /logs/webserver.pcap /logs/extract_logs.zeek;"]